insert into CongThuc (Ma_Mon, Ma_NguyenLieu, SoLuong) values (1, 2, 2);
insert into CongThuc (Ma_Mon, Ma_NguyenLieu, SoLuong) values (1, 4, 2);
insert into CongThuc (Ma_Mon, Ma_NguyenLieu, SoLuong) values (3, 2, 2);
insert into CongThuc (Ma_Mon, Ma_NguyenLieu, SoLuong) values (4,9, 1);
insert into CongThuc (Ma_Mon, Ma_NguyenLieu, SoLuong) values (2, 8, 3);
insert into CongThuc (Ma_Mon, Ma_NguyenLieu, SoLuong) values (10, 8, 5);
insert into CongThuc (Ma_Mon, Ma_NguyenLieu, SoLuong) values (9, 11, 1);
insert into CongThuc (Ma_Mon, Ma_NguyenLieu, SoLuong) values (7, 3, 5);
insert into CongThuc (Ma_Mon, Ma_NguyenLieu, SoLuong) values (7, 1, 1);
insert into CongThuc (Ma_Mon, Ma_NguyenLieu, SoLuong) values (10, 2, 3);
